github.com:
    users:
        zooolaaalaa:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: zooolaaalaa
